services:
  backend:
    image: ghcr.io/unidank/pentaquest-backend:refactor
    environment:
      - DB_URL=mongodb://pentaquest:example@mongodb:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pentaquest
      MONGO_INITDB_ROOT_PASSWORD: example